# Python list va NumPy tezligini taqqoslash
100 000 ta qiymatni 10 marta ikkiga ko'paytirish vaqtini solishtiramiz.

In [1]:
import time
import numpy as np

In [2]:
my_list = list(range(100000))
my_array = np.array(range(100000))

In [4]:
%time for _ in range(10): my_array * 2

CPU times: total: 0 ns
Wall time: 1.11 ms


In [5]:
%time for _ in range(10):[x * 2 for x in my_list]

CPU times: total: 109 ms
Wall time: 107 ms


In [6]:
107/1.1

97.27272727272727

In [ ]:
data1 = [23, 3.4, 7, 9, 5] #list of numbers
arr1 = np.array(data1)
arr1

array([23. ,  3.4,  7. ,  9. ,  5. ])

In [14]:
data2 = (2, 9.4, 3, 4, 1) #tuple of numbers
arr2 = np.array(data2)
arr2

array([2. , 9.4, 3. , 4. , 1. ])

In [15]:
arr1.ndim #array1 ning o'lchami

1

In [16]:
arr2.ndim 

1

In [26]:
data3 = [[1,3,4], [3,1,5,], [1,2,3]] #list of lists
arr3 = np.array(data3) #array3 ning o'lchami

In [28]:
data3

[[1, 3, 4], [3, 1, 5], [1, 2, 3]]

In [33]:
arr3

array([[1, 3, 4],
       [3, 1, 5],
       [1, 2, 3]])

In [29]:
arr3.shape

(3, 3)

In [30]:
arr3.size

9

In [ ]:
# n o'lchovli massivlarni yaratish boshqa usullari
arr4 = np.zeros((3, 4)) #3 qator va 4 ustunli massiv 0 ga teng bo'ladi
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
arr5 = np.ones((3,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
arr6 = np.arange(4,20,2) #4 dan 20 gacha bo'lgan sonlar 2 qadam bilan
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr7 = np.arange(20) #0 dan 20 gacha bo'lgan sonlar 1 qadam bilan
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
#Yangi mavzu 


In [41]:
arr1 = np.array ([1, 2, 3], dtype = np.float32) #array1 ni float32 tipida yaratish
arr1

array([1., 2., 3.], dtype=float32)

In [43]:
arr2 = np.array ([1,2,3], dtype = np.int32) #array2 ni int32 tipida yaratish
arr2

array([1, 2, 3], dtype=int32)

In [44]:
arr1.dtype

dtype('float32')

In [45]:
arr2.dtype

dtype('int32')

In [46]:
arr = np.array ([1,2,3,4]) #int 64
arr

array([1, 2, 3, 4])

In [47]:
#astype metodi
float_arr = arr.astype(np.float32)
float_arr

array([1., 2., 3., 4.], dtype=float32)

In [49]:
data = np.array([1.4, 2.7, 3.2, 4.9, 5]) #float64 tipidagi massiv
int_data = data.astype(np.int32) 
int_data

array([1, 2, 3, 4, 5], dtype=int32)

In [8]:
#indexlash va kesish
import numpy as np
import time
arr = np.arange(10, 100, 10) 
arr[1]

np.int64(20)

In [12]:
arr [3:5]  # kesib olish

array([40, 50])

In [15]:
#kesib olish slice 
arr
sliced_arr = arr[3:5]
sliced_arr [:]
sliced_arr

array([40, 50])

In [3]:
import numpy as np
arr4 = np.arange(10, 1000, 50)
arr4

array([ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460, 510, 560, 610,
       660, 710, 760, 810, 860, 910, 960])